### ISSUE TITLE
После установки обнаружилась проблема при открытии vim

### ISSUE THREAD

**Issue by Andrew8xx8** [gumayunov/homedir#3]
Error detected while processing /home/akulakov/.vim/vimrc:
line  316:
E484: Can't open file /home/akulakov/vimfiles/snippets/support_functions.vim

**Comment by gumayunov** [comment]
Для ее устранения я сделал следующее:

```
cd ~/.vim
git submodule update
```

И все заработало. В чем прикол — пока не понятно

**Comment by zzet** [comment]
забавно. https://github.com/akitaonrails/vimfiles написано "git submodule update --init", однако ошибка также сыпалась. Если без инита - то все заработало. Mac OS.

**Comment by gumayunov** [comment]
с нуля поставил на линуксе - все ок
